# Generated by Django 5.2.3 on 2025-06-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_url_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='method',
            field=models.CharField(default='random', max_length=10),
        ),
    ]
